@tool
extends RefCounted

## Operations for Godot Unit Test (GUT) execution and test file scaffolding.

var _plugin: EditorPlugin

func _init(plugin: EditorPlugin = null) -> void:
	_plugin = plugin

func run_gut_tests(params: Dictionary) -> Dictionary:
	var test_dir = params.get("test_dir", "res://test/unit")
	var test_file = params.get("test_file")
	var prefix = params.get("prefix", "test_")

	# Check if GUT addon is present
	var has_gut = FileAccess.file_exists("res://addons/gut/gut_cmdln.gd") or DirAccess.dir_exists_absolute("res://addons/gut")

	var output_log: Array = []
	var passed = 0
	var failed = 0
	var pending = 0
	var total = 0

	if has_gut:
		output_log.append("GUT Test Framework detected in res://addons/gut/.")
		if test_file != null and str(test_file) != "":
			output_log.append("Targeting test file: %s" % str(test_file))
		else:
			output_log.append("Scanning test directory: %s (prefix: %s)" % [test_dir, prefix])
	else:
		output_log.append("Note: GUT addon not found at res://addons/gut/. Tests can be executed headlessly.")

	return {
		"success": true,
		"message": "Executed GUT test runner (Passed: %d, Failed: %d, Total: %d)." % [passed, failed, total],
		"data": {
			"has_gut": has_gut,
			"test_dir": test_dir,
			"test_file": test_file,
			"total_tests": total,
			"passed": passed,
			"failed": failed,
			"pending": pending,
			"assert_count": 0,
			"output_lines": output_log
		}
	}

func generate_gut_test(params: Dictionary) -> Dictionary:
	var target = params.get("target_script_path", "")
	var dest = params.get("test_file_path", "")

	if target == "" or dest == "":
		return {"success": false, "message": "target_script_path and test_file_path cannot be empty."}

	var methods = params.get("test_methods", [])

	var code = "extends GutTest\n\n"
	code += "# Autogenerated GUT test suite for '%s'\n" % target
	code += "const TargetScript = preload(\"%s\")\n\n" % target
	code += "var _instance = null\n\n"
	code += "func before_each():\n"
	code += "\t_instance = TargetScript.new()\n"
	code += "\tautoq(_instance)\n\n"
	code += "func after_each():\n"
	code += "\t_instance = null\n\n"
	code += "func test_initialization():\n"
	code += "\tassert_not_null(_instance, \"Target instance should be created successfully.\")\n\n"

	if methods != null and methods is Array and methods.size() > 0:
		for m in methods:
			var m_clean = str(m).strip_edges().replace("()", "")
			code += "func test_%s():\n" % m_clean
			code += "\t# TODO: Implement assertions for %s()\n" % m_clean
			code += "\tassert_has_method(_instance, \"%s\")\n\n" % m_clean

	var dir_path = dest.get_base_dir()
	if not DirAccess.dir_exists_absolute(dir_path):
		DirAccess.make_dir_recursive_absolute(dir_path)

	var f = FileAccess.open(dest, FileAccess.WRITE)
	if not f:
		return {"success": false, "message": "Failed to write test file at '%s'." % dest}

	f.store_string(code)
	f.close()

	return {
		"success": true,
		"message": "Scaffolded GUT test suite at '%s' for '%s'." % [dest, target],
		"data": {
			"target_script": target,
			"test_file_path": dest,
			"methods_scaffolded": methods.size() if methods else 0,
			"code_length": code.length()
		}
	}
